#ifndef SRC_SUPLA_Z2S_CUSTOM_ACTIONS_EVENTS_H_
#define SRC_SUPLA_Z2S_CUSTOM_ACTIONS_EVENTS_H_

#define Z2S_SUPLA_ACTION_BASE                             0x4000

#define Z2S_SUPLA_ACTION_IAS_NOTIFICATIONS_ON             0x4000
#define Z2S_SUPLA_ACTION_IAS_NOTIFICATIONS_OFF            0x4001
#define Z2S_SUPLA_ACTION_DEVICE_STATUS_CHANGE             0x4010

#define Z2S_SUPLA_ACTION_START_TIMER                      0x4020
#define Z2S_SUPLA_ACTION_STOP_TIMER                       0x4021
//#define Z2S_SUPLA_ACTION_RESTART_GATEWAY                  0x4100

#define Z2S_SUPLA_ACTION_TURN_ON_MAX_TEMPERATURE          0x5000
#define Z2S_SUPLA_ACTION_TURN_ON_MIN_TEMPERATURE          0x5001

#define Z2S_SUPLA_ACTION_RESEND_RELAY_STATE               0x5100

#define Z2S_SUPLA_EVENT_BASE                              0x4000

#define Z2S_SUPLA_EVENT_ON_SUPLA_INITIALIZED              0x4009
#define Z2S_SUPLA_EVENT_ON_SUPLA_REGISTERED_AND_READY     0x4010
#define Z2S_SUPLA_EVENT_ON_ZIGBEE_STARTED                 0x4020

#define Z2S_SUPLA_EVENT_ON_EVERY_5_SECONDS                0x4100
#define Z2S_SUPLA_EVENT_ON_EVERY_30_SECONDS               0x4101
#define Z2S_SUPLA_EVENT_ON_EVERY_60_SECONDS               0x4102
#define Z2S_SUPLA_EVENT_ON_EVERY_24_HOURS                 0x4150


#endif //