name: Build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2
      - name: Install platform
        run: |
          arduino-cli core install esp32:esp32
      - name: Compile Sketch
        working-directory: ./examples/Z2S_Gateway/
        run: arduino-cli compile -b esp32:esp32:esp32c6 -e --build-property="compiler.cpp.extra_flags=\"\""
#      - name: Upload bin
#        uses: actions/upload-artifact@v2
#        with:
#          name: ${{ matrix.core_a}}_${{ matrix.core_b }}_${{ matrix.board }}_${{ matrix.apn }}
#          path: ./microcontroller/build/${{ matrix.core_a}}.${{ matrix.core_b }}.${{ matrix.board }}/microcontroller.ino.bin
