name: Build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2
      - name: Install platform
        run: |
          arduino-cli core install esp32:esp32
          arduino-cli lib install SuplaDevice
      - name: Copy boards.txt with C6 config
        run: | 
          cp ./partitions/boards.txt ~/.arduino15/packages/esp32/hardware/esp32/3.1.1/boards.txt
          cp ./partitions/custom_zigbee_zczr.csv ~/.arduino15/packages/esp32/hardware/esp32/3.1.1/tools/partitions/custom_zigbee_zczr.csv
      - name: Compile Sketch
        working-directory: .
        run: arduino-cli compile ./examples/Z2S_Gateway -b esp32:esp32:esp32c6:PartitionScheme=custom,ZigbeeMode=zczr -e --library=. --libraries=SuplaDevice 
      - name: Upload bin
        uses: actions/upload-artifact@v4.6.0
        with:
          name: Z2S_Gateway.Webinteface.bin
          path: ./build/Z2S_Gateway.ino.bin
