name: Build
on: [workflow_dispatch]
jobs:
  build:
    name: Build and create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/cache@v4
        with:
          path: |
            ~/.arduino15/packages/
          key: ${{ runner.os }}-arduino      
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2
      - name: Install platform
        run: |
          arduino-cli config init
          arduino-cli config set board_manager.additional_urls "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json"
          arduino-cli config set library.enable_unsafe_install true
          arduino-cli core update-index
          arduino-cli core install esp32:esp32@3.1.3
          arduino-cli lib install --git-url https://github.com/SUPLA/supla-device.git
          arduino-cli lib install --git-url https://github.com/LennartHennigs/ESPTelnet.git
          arduino-cli lib install --git-url https://github.com/adafruit/Adafruit_NeoPixel.git
          arduino-cli lib install --git-url https://github.com/dojyorin/arduino_base64.git
      - name: Copy boards.txt with C6 config
        run: | 
          cp ./partitions/boards313.txt ~/.arduino15/packages/esp32/hardware/esp32/3.1.3/boards.txt
          cp ./partitions/custom_zigbee_zczr.csv ~/.arduino15/packages/esp32/hardware/esp32/3.1.3/tools/partitions/custom_zigbee_zczr.csv
      - name: Compile Gateway_8MB_logs
        working-directory: .
        run: arduino-cli compile ./examples/Z2S_Gateway -b esp32:esp32:esp32c6:PartitionScheme=zigbee_zczr_8MB,ZigbeeMode=zczr,FlashSize=8M,CDCOnBoot=cdc,DebugLevel=debug -e --library=. --libraries=SuplaDevice
     
      

